// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYxWjKVO-NhsYC0wWtzHX24CIhYxLiSvM',
    appId: '1:810649785265:web:509e7834cea296d363e390',
    messagingSenderId: '810649785265',
    projectId: 'gitgossip-yash',
    authDomain: 'gitgossip-yash.firebaseapp.com',
    storageBucket: 'gitgossip-yash.firebasestorage.app',
    measurementId: 'G-CELGZYN882',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZC9DdZ8q4Z8HVbCc69w91LRlhHC_IceE',
    appId: '1:810649785265:android:0295f6ca15cc630963e390',
    messagingSenderId: '810649785265',
    projectId: 'gitgossip-yash',
    storageBucket: 'gitgossip-yash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbnbMQCnyz9trFFS1WOlW0uFQzDTP3_rg',
    appId: '1:810649785265:ios:63857e1cfda3f94363e390',
    messagingSenderId: '810649785265',
    projectId: 'gitgossip-yash',
    storageBucket: 'gitgossip-yash.firebasestorage.app',
    androidClientId: '810649785265-7tmmmng2f2srnvsratsob8oqvugf4cd7.apps.googleusercontent.com',
    iosClientId: '810649785265-goj1kroqrjmmr6bdi7o757vdjnt47fgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.gitgossip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbnbMQCnyz9trFFS1WOlW0uFQzDTP3_rg',
    appId: '1:810649785265:ios:63857e1cfda3f94363e390',
    messagingSenderId: '810649785265',
    projectId: 'gitgossip-yash',
    storageBucket: 'gitgossip-yash.firebasestorage.app',
    androidClientId: '810649785265-7tmmmng2f2srnvsratsob8oqvugf4cd7.apps.googleusercontent.com',
    iosClientId: '810649785265-goj1kroqrjmmr6bdi7o757vdjnt47fgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.gitgossip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYxWjKVO-NhsYC0wWtzHX24CIhYxLiSvM',
    appId: '1:810649785265:web:8b39aa7d84b5952c63e390',
    messagingSenderId: '810649785265',
    projectId: 'gitgossip-yash',
    authDomain: 'gitgossip-yash.firebaseapp.com',
    storageBucket: 'gitgossip-yash.firebasestorage.app',
    measurementId: 'G-0KY32T1YGM',
  );

}