// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtRYkWmZAwBMIgRi3o-sFyD2PWWktYIU8',
    appId: '1:586335171290:web:515a06344344f2e6be6be3',
    messagingSenderId: '586335171290',
    projectId: 'gitgossipapp',
    authDomain: 'gitgossipapp.firebaseapp.com',
    storageBucket: 'gitgossipapp.firebasestorage.app',
    measurementId: 'G-5R45N7YNVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPmWQTCUEAy4khDgqhrgdoFn5MyHvdxCw',
    appId: '1:586335171290:android:4238afcfe6a2c214be6be3',
    messagingSenderId: '586335171290',
    projectId: 'gitgossipapp',
    storageBucket: 'gitgossipapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7gsd9CSvwAhCPiTmLYHRwPdudGlpnzFk',
    appId: '1:586335171290:ios:a3c6f7e5f89d1811be6be3',
    messagingSenderId: '586335171290',
    projectId: 'gitgossipapp',
    storageBucket: 'gitgossipapp.firebasestorage.app',
    iosBundleId: 'com.example.gitgossip',
  );
}
