// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARmjdLHa-6uc3Fb9sUUdFPMywtw5vNbHA',
    appId: '1:622479540982:web:021ef35fbc7a70909e22d7',
    messagingSenderId: '622479540982',
    projectId: 'gitgossip-62e31',
    authDomain: 'gitgossip-62e31.firebaseapp.com',
    storageBucket: 'gitgossip-62e31.firebasestorage.app',
    measurementId: 'G-G0J6LR87FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjvV5eSOPt5-rOyvKqrxUPfMSXMoCO2Tc',
    appId: '1:622479540982:android:e9e6ac458aabadef9e22d7',
    messagingSenderId: '622479540982',
    projectId: 'gitgossip-62e31',
    storageBucket: 'gitgossip-62e31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_m6cpchLJFxNihcuINhmZgEZWAn_-9sk',
    appId: '1:622479540982:ios:f1e28e3c1d2a42809e22d7',
    messagingSenderId: '622479540982',
    projectId: 'gitgossip-62e31',
    storageBucket: 'gitgossip-62e31.firebasestorage.app',
    iosBundleId: 'com.example.gitgossip',
  );
}
